version: "3.8"

services:
  postgres_database:
    image: postgres:14.4-alpine3.16
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    container_name: "todo-postgres"

  flyway:
    depends_on:
      - postgres_database
    image: "info7205group5/db:latest"
    environment:
      - dbhost=postgres_database
      - dbport=5432
      - db=${POSTGRES_DB}
      - username=${POSTGRES_USER}
      - password=${POSTGRES_PASSWORD}
      - schema=todo
    command: -connectRetries=60
    container_name: "todo-flyway"

  app:
    depends_on:
      - postgres_database
      - flyway
    image: "info7205group5/app:latest"
    environment:
      - dbhost=postgres_database
      - dbport=5432
      - db=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    container_name: "todo-application"